import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <script
          src="https://code.jquery.com/jquery-3.2.1.min.js"
          defer
        ></script>
        <script
          src="https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey=VqMhcfR29p90wnyQM6IsS9jccnNyJfQF0DVa6do7"
          defer
        ></script>
        <div className="--font-pretendard">{children}</div>
      </body>
    </html>
  );
}
